import Head from "next/head";

const SimpleLayout = ({ children }) => {
  return (
    <div className="color-black-900 bg-gray-50 p-16 flex flex-col items-center justify-center h-screen">
      <Head>
        <title>mintcart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-16 max-w-3xl	w-full shadow-xl bg-white">
        {children}
      </main>
    </div>
  );
};

export default SimpleLayout;
