import Head from "next/head";

const SimpleLayout = ({ children }) => {
  return (
    <div className=" p-8 md:p-16 flex md:flex-col md:items-center justify-center md:color-black-900 bg-gray-50 md:h-screen">
      <Head>
        <title>mintcart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:p-16 max-w-3xl	w-full md:shadow-xl bg-white">
        {children}
      </main>
    </div>
  );
};

export default SimpleLayout;
